language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_existing: true
  user: msk-access
  password:
    secure: dDWuxl36FoMKaefpA3wD2WuwflVUFFRFA2Dwp8+BD/xQHCLxZbBgq+pOlj/xZlwmAqS/w8FihXYZTSnDKIgQYcr/SdWl6yuCgc36IzhyJ2xfvHCG8mBejFX8+qfsB+5hMM/tvNtprg/WIJB4Z1xk7n3wz/g0SR6oTx6Z20G+tbOEw6ivKv1ASMlQjvSZdIMku/foyMsfKdzZYeYLpQpgkyqRuba8O66IjU4fMYfUNIdyGhXNIMR0O9tzb4nj6/dwytEEn8NI7RQDL4sFk5OputwMGwKA4bKiFEC0zJ3wyil9IIjfBhBZyyo4hmFwdrAhYJXixaMB9YqbAMoHjib/Bh23mpscM6s/YWEkhE0LHGJgGrBifsrD96uzXEyaXExNq4iLEDdDOfaMuo3oDqDMyLiQfQX/qWorRf/7nF6LdqD1uiz1Jhxy9jcjLxrKqUvcV3RfBFX0riS8x5DkRLk5qZNbYQ/rfMzKQRRUnE2/YaFI8S//4of7p69KiJVDD48qRPyILN6i2Q2OfRU1skOn9y2dUPvpFvFnFeT7l3mO4u5HYNn4c/c//TvmoljCdCDnYoKuWoo1yADJVzanUj4FCA0iNvb/XW0Q+G4hmcmqsMCk8OX3lP0NpZdPSRjHFP3WaW8nNpWfBMSu5MjBCjECLxLsGLXjjokNuZ75W/gYRak=
  true:
    tags: true
    repo: msk-access/merge_fastq
    python: 3.7
