language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: msk-access
  password:
    secure: WEYT0nW0RzZTsXh/ctKQlKVFNAdF9vHdybo8JaI+A7zir3Gzg6j2mFk1PJDJSbEk7CzsieSbIXGuSigrFq8MNGJvbLDqESSgTNSMmncedTiYwbMJ7kECTs79Z7PaMIFnZTOhzcXPhIfgqDBdX8Toyhy9Lhq5NeaYql4ayT6V9ZMQnb7yCE+bjg+QSeh7/O+uvX6t0LrklbQezryONR6Fld4HijD2mGif/M1Bt3xVIsuT5Gvjs5gmWjCHcW4s1yuIQdYI1m9Q/Wb6xDKAW1gF6V9SkrCDLlXS7MQAjXO5WtoMzc/qqPVGDDAoYNGx5agyX1xnvtv1VpRXp1zBmpBSdQm38mt+dyeof5gtKt2d7+yJJBcliZfEheu9s7UzAbOGTULihhBvuV0tk4+wB5FChvw6A8hgFeuYLO9iknFdPOI4BxyYNsaOfcWmeGXr7wH4RuK55Q5Jv4nCuKfQQYip+0X0F43dEefuT5+5IfTokNaICBSoBffNnoTyOxKey41V9SgSi4AP2AaCz24XXvcIMPVy3f48GKAYibtN4XvlPGH800m5/14eKKuPJyRZzqd3fVOdLWKfmMEX2Ln6gbucuVwYXPs82dhE2r3Gb3M0rosclbrbptfvoFrBrD7ofZeeRMQTM0NrYK7NHL+7tTOfwCycFkx+m8s6Ff3iif0c4cc=
  true:
    tags: true
    repo: msk-access/merge_fastq
    python: 3.7
