language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_existing: true
  user: msk-access
  password:
    secure: "P7pJp3xWX3pFXONSJQAYzNOmODk+mhnRlxQ9qBjm5RCLa1eiCE5rhtRa1m257L24Z/Aalnc1bxzqTm71SFU1wZBwh6kXKq1mDF2RoTg7dYL9Gq4g6cuKR0KJU9booduL2bCz8Gx7f4MELmWc1vYBsWJzhq2ojZ2Nye6rSgfx6RNCWvsunPt/VNNiamqNeuVcTswtDsPDSedO2ypl7x8OGc+F3JcFGymjEuAz3uWSz8FVB59pvJ8GJryJL0BDFTG1xOzkWG/zh51+OFauFERkWI8VCgl98dNG2hcSFuCHiHFYw+C10hb9XWY6mxvPboocHSUqZoQK9+YA0gCpaBZ0vUd+1GTDYbo2EQC+I9sB+gypI+SfHgzhVkk6V7T16AHkfut4xWnig5Z6Ni16Jp7Yr7G0g0eJRpfHc8AyRWh2dGliVLG6ZlX7kcwZmNlojsyt6S6haKGsxdSuSuCPtqsLAR/f51OOKKXp7PUKjkEUyeHFWc1wcomV6DNUYsQllyeBNPpcWvY/9MoC+fBV8S3z8HX0Vdy8PXgpmc4/ggqwNNaXdBcqia7NY0fcXJkp4L/nFWGxeUt61w/QaqtcIj4OYo4aWlLuz3OSDko27W7r4oNlcwPXkubUHGS24JMOvYS7ejlg985N0Ru55dYA4C5xP4honjk5XtF+FXxqSLtQWtQ="
  true:
    tags: true
    repo: msk-access/merge_fastq
    python: 3.7
