language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: msk-access
  password:
    secure: UnLWFy1LF9sY4lhZDyUmcOqFThZ/EyMz2W6RkbMeK9bWQuUy9HvCcyNmfA/bwlZ7tAGPfcueCFw6lcLPDjPOdkReYMWYK8xk/obg2gT7Jrk+Ffa3TuFrsB97FkpcFcw7cVPWx0yiWE5Mb7+ellRcU4RXfyxGVCY6p41bUSv6ZWaqC08pxGdq3LIKJhBPnmAWu/FLO4YVM3Ur+q6wsADoLc8ckw4LmGRSd0kJN/C88rjxn3wGbaVH9T+X4XwZHw2Wnj8sYqekv1M3bbctTvdj8CKOh9M2XWwWfhkoVv3MY9zZTgxz4tKR4iiL4N0JCs+/mZYBuRh0Htv02FV1s3t3/29bbAFNa7S1SNNiZjxF7HanPkHqTiJ/GxtWo9kwkAtUzSv3YYoYh8DyCazHzd3E7Wc5xiPaUH6iAqjC4FbWmxazSogjz/KvUdEMUjkbnI8Ww8HudCzHoC7y61pUsNp4k/S2LbETD6TW07VDLwbe1Xb0KXcHABe4uhUxrVUgZdN5sC0WANZswUoe6S+X0ZRYNwyzQe9SX4EZa6wyKZVtBdVI0t8jPl1sHSyItLLcH9PKROLC7b8iuqtzPVo5zFEl643L9hfXgDkKkXjfqfy05/jR9wkRV0MG0uurm8jJf9TjWQN0BNdz4KiAcN6jtfh62cQwzA1OHMLFoH35vYphclI=
  true:
    tags: true
    repo: msk-access/merge_fastq
    python: 3.7
