language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_existing: true
  user: msk-access
  password:
    secure: JxjnUbDC4i5ghhMqPz9clG24DA0cXzHEl/VUfxd4f2UzQxqO1T9Va7GRiJK20Ol5nPTe1KfkSMr11+/xjkpOdcd15CpuKSODwoPb+UowGaq2ionKXPNAtcROgzAF18q+wIN09JiwH3COD5hHs4/VrZ2RKLoQu7y19rJJL8JIKfG1EWjlQ7WERoM3Hs455oNqxWVZv3HHN+hKILV8jrNHMqMxIZtOH+HewIewWu8W+6LnAHEjcRN0qRal1E5OFTN8kOgadVe9FXjpM4ElhevmLJoGbLnFmb3wOpX9eODAiAdeSg+DsFp84h6MckjhdRJQQraVMZPQ/sI5mWxsC69rGOdxtgSxkk6qWE3crO3Ummy2/95HJu/g1fnxUVs679ahRZBtMW/wvSqu+s40z1WCfef+ySr44ptfXVltlDUk1m31S0tW6je+byn/aDbDcvDQIQm9aFiEuqM9zo2FshL361Z4X/jYr7OhyEya3PJy+LNjIDfyc7FHN1R1Y4a9Rb3ToangjZU/XprUmmlV7SaFG6xbSTDszMeH+tJjabo32tIKkyoTcr990VSdoPk49usUJ7zvzXCWJ+vrBAzlxj0fUdwhVhYHrqYjvYS8/BmRL9KGeZpOWaHp8Dh+m46nhvyasN3yl7CsLVM5Ogny921zdH4IjbwRFadAlTWDKcSdfBo=
  true:
    tags: true
    repo: msk-access/merge_fastq
    python: 3.7
